// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmK5wDUw0CL1jpZQDH3BDCZemfArCJosU',
    appId: '1:105970645277:web:0db912103e551e9e11c9f4',
    messagingSenderId: '105970645277',
    projectId: 'geotour-b54c1',
    authDomain: 'geotour-b54c1.firebaseapp.com',
    storageBucket: 'geotour-b54c1.firebasestorage.app',
    measurementId: 'G-NB0TY9ZGJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSi-1XosL_G1EGsUKGKu9UZ-SriwLtJOI',
    appId: '1:105970645277:android:302ecfe7c721425911c9f4',
    messagingSenderId: '105970645277',
    projectId: 'geotour-b54c1',
    storageBucket: 'geotour-b54c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBioU0yQuAy2qombGFtbxV4j95NXE76hkU',
    appId: '1:105970645277:ios:e800c74642c1fbcf11c9f4',
    messagingSenderId: '105970645277',
    projectId: 'geotour-b54c1',
    storageBucket: 'geotour-b54c1.firebasestorage.app',
    androidClientId: '105970645277-cjajufbh5v4h7glrgv36bu8qih3cdteb.apps.googleusercontent.com',
    iosClientId: '105970645277-36uadjo6ld07eftd3d9l4vijqoinu1j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBioU0yQuAy2qombGFtbxV4j95NXE76hkU',
    appId: '1:105970645277:ios:e800c74642c1fbcf11c9f4',
    messagingSenderId: '105970645277',
    projectId: 'geotour-b54c1',
    storageBucket: 'geotour-b54c1.firebasestorage.app',
    androidClientId: '105970645277-cjajufbh5v4h7glrgv36bu8qih3cdteb.apps.googleusercontent.com',
    iosClientId: '105970645277-36uadjo6ld07eftd3d9l4vijqoinu1j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmK5wDUw0CL1jpZQDH3BDCZemfArCJosU',
    appId: '1:105970645277:web:7695dce25670674411c9f4',
    messagingSenderId: '105970645277',
    projectId: 'geotour-b54c1',
    authDomain: 'geotour-b54c1.firebaseapp.com',
    storageBucket: 'geotour-b54c1.firebasestorage.app',
    measurementId: 'G-JNR98N1G8E',
  );

}